Перевел пункт 11. Итераторы и Генераторы
leonidlebedev/javascript-airbnb pull request #1
Opened 2016-12-28 16:19 UTC by nialvi

пляж

2016-12-28 21:31 UTC, leonidlebedev requested changes
Нужна доработка.

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +  <a name="iterators-and-generators"></a><a name="11.1"></a>
Не надо менять названия якоря, т.к. он связан с той ссылкой внизу

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    > Почему? Лучше использовать правила имутабельности (immutable). Работать с чистыми функциями лучше для понимания, чем с фукциями с side effect-ами.
`side effect` — побочные эффекты. До этого переводил полностью на русский, поэтому может нужно оставить только русский вариант.

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    // отлично (используй функциональную силу)
Стиль перевода направлен к Разработчику, т.е. обращение на Вы.
Правильно: _Используйте_.
Также склоняюсь больше к переводу “Используйте силу функций“. Звучит красивее.

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    // отлично (и тут используй функциональную силу)
Не могу что-то придумать, но как-то тоже не так 
Хочется что-то в духе: "Продолжайте в том же духе", "Сохраняйте силу функций"

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +  - [11.3](#generators--spacing) Если все таки нужно использовать генераторы, или не обратили внимания на [наш совет](#generators--nope), убедитесь, что * у функции генератора расположена должным обр
вместо нужно — необходимо, т.к. must — является самым сильным в эмоциональном плане глаголом среди других модальных глаголов. [Полезно будет](http://online-teacher.ru/blog/anglijskaya-grammatika-modalnye-glagoly)
все-таки
 , * поместить в `` => `*`

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    > Почему? `function` и `*` два разные зарезервированные конструкции. `*` не является модификатором для `function`, `function*` является уникальной конструкцией, отличается от `function`.
`function` и `*` являются частью одного и того же ключевого слова.

отличной от

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +## Итераторы и генераторы
Здесь нужно добавить ссылку с ярлыком, иначе нельзя перейти от оглавление к этому пункту. Как пример, смотри переведённые пункты

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +  - [11.1](#iterators--nope) Не используйте итераторы. Лучше использовать функции высшего порядка, вместо таких циклов как `for-in` или `for-of`. eslint: [`no-iterator`](http://eslint.org/docs/rules/
Используйте, использовать.
Можно заменить фразу `Лучше использовать` на `Применяйте`, `Предпочитайте`, `Выбирайте`
Может что-то лучше есть

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    > Почему? Лучше использовать правила имутабельности (immutable). Работать с чистыми функциями лучше для понимания, чем с фукциями с side effect-ами.
имМутабельность + слово на английском не нужно, т.к. первый поиск в гугле показывает нужное определение.

2016-12-28 21:31 UTC, leonidlebedev commented on README.md
> +    > Почему? Лучше использовать правила имутабельности (immutable). Работать с чистыми функциями лучше для понимания, чем с фукциями с side effect-ами.
А ещё здесь объясняется причина, поэтому тут текст почему мы не должны использовать итераторы. А перевод продолжает предлагать, а не объяснять позицию.

Почему?
Да потому что мы придерживаемся правила о неизменяемости объекта.

`Это обеспечивает соблюдение нашего правила об иммутабельности. Работать с чистыми функциями, которые возвращают значение, лучше для понимания, чем с фуНкциями с побочными эффектами.`

2017-01-01 21:07 UTC, VictoriaMaksimova requested changes

2017-01-01 21:07 UTC, VictoriaMaksimova commented on README.md
> +    > Используйте `map()` / `every()` / `filter()` / `find()` / `findIndex()` / `reduce()` / `some()` / ... для итерации по массивам, а `Object.keys()` / `Object.values()` / `Object.entries()` для со
После "которых" перед "можно" не нужна запятая

2017-01-01 21:07 UTC, VictoriaMaksimova commented on README.md
> +  - [11.3](#generators--spacing) Если все таки нужно использовать генераторы, или не обратили внимания на [наш совет](#generators--nope), убедитесь, что * у функции генератора расположена должным обр
"все-таки" через дефис
И кажется вот так "или вы не обратили", добавить "вы"

2017-01-08 11:21 UTC, leonidlebedev commented
@nialvi, исправь, пожалуйста :blush:

2017-01-08 13:09 UTC, nialvi commented on README.md
> +    // отлично (используй функциональную силу)
может оставить? отсылка к Люку)
Смысл шутки теряется

Плюс functional тут как прилагательное. Функциональное программирование -- функциональная сила

2017-01-08 13:11 UTC, nialvi commented on README.md
> +    // отлично (и тут используй функциональную силу)
оставил Продолжайте в том же духе

2017-01-08 18:39 UTC, VictoriaMaksimova requested changes

2017-01-08 18:39 UTC, VictoriaMaksimova commented on README.md
> +  - [11.1](#iterators--nope) Не используйте итераторы. Применяйте функции высшего порядка, вместо таких циклов как `for-in` или `for-of`. eslint: [`no-iterator`](http://eslint.org/docs/rules/no-itera
Не надо запятой после `порядка`

2017-01-08 19:00 UTC, leonidlebedev commented on README.md
> +    // отлично (используй функциональную силу)
Что это такое _функциональная сила_?

2017-01-10 22:06 UTC, leonidlebedev approved these changes

2017-01-11 23:06 UTC, VictoriaMaksimova approved these changes

2017-01-12 06:42 UTC, merged