#6. Строки
leonidlebedev/javascript-airbnb pull request #11
Opened 2017-01-02 11:21 UTC by leonidlebedev

2017-01-02 14:36 UTC, VictoriaMaksimova requested changes

2017-01-02 14:36 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Шаблонные строки дают вам читабельность, лаконичный синтаксис с правильными символами перевода строк и функции интерполяции строки.
Тут кажется слово `функции` не согласовано, должно быть видимо `функцией`

2017-01-02 14:36 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Обрытные косые черты ухудшают читабельность, поэтому они должны присутствовать только при необходимости.
опечатка, `Обрытные`

2017-01-02 15:14 UTC, leonidlebedev commented on README.md
> +    > Почему? Шаблонные строки дают вам читабельность, лаконичный синтаксис с правильными символами перевода строк и функции интерполяции строки.
Дают
- читабельность
- лаконичный синтаксис
- функции

2017-01-02 20:50 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Шаблонные строки дают вам читабельность, лаконичный синтаксис с правильными символами перевода строк и функции интерполяции строки.
Аа)

2017-01-03 10:30 UTC, VictoriaMaksimova approved these changes

2017-01-03 11:32 UTC, merged

2017-01-14 21:25 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Шаблонные строки дают вам читабельность, лаконичный синтаксис с правильными символами перевода строк и функции интерполяции строки.
@leonidlebedev 
Как-то у меня на этой фразе всё-таки спотыкается глаз. Именно функциИ, их много? Или может функциЮ?