#7. Функции
leonidlebedev/javascript-airbnb pull request #12
Opened 2017-01-02 13:18 UTC by leonidlebedev

2017-01-02 20:18 UTC, VictoriaMaksimova requested changes

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле. Это вредит читабельности и поддержки. Если вы обнаружите, что определ
Должно быть `е` в конце - `Это вредит читабельности и поддержке`
Опечатка `пониманить`
Можно убрать чтобы и запятую, а то предложение и так длинное и сложное - `пришло время извлечь его в отдельный модуль!`
Опечатка `фукнциональные`

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Самовызывающееся функциональное выражение представляет собой единый блок, чтобы четко показать это, оберните вызывающие скобки в скобки. Обратите внимание, что в мире с модулями, вам бо
Я бы так перевела `Самовызывающееся функциональное выражение представляет собой единый блок. Чтобы четко показать это, оберните его само и вызывающие скобки ещё в одни скобки`
Ещё меня терзают сомнения по поводу `Самовызывающееся`. Кажется, в литературе я встречала термин "немедленно вызываемые"
Не нужна запятая `с модулями, вам больше`
Не согласовано `не нужны самовызывающееся функциональное выражение`

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +  - [7.4](#functions--note-on-blocks) **Примечание:** ECMA-262 определяет блок как список инструкций. Объявление функции не является инструкцией. [Подробнее в документе ECMA-262](http://www.ecma-inte
слово `блок` надо взять в косые кавычки как в оригинале

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +  - [7.6](#es6-rest) Никогда не используйте `arguments`, вместо этого используйте оператор расширения eslint: [`prefer-rest-params`](http://eslint.org/docs/rules/prefer-rest-params)
может быть добавить три точки как в оригинале `оператор расширения ...`

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? `...` явно говорит о том, какие именно аргументы вы хотите вытащить. Кроме того, аргументы оператора расширения являются настоящим массивом, а не массиво-подобным как `arguments`.
Не хватает слова `объектом` - `а не массиво-подобным объектом как`

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Хорошая консистенция, и вам не надо будет добавлять или удалять пробел при добавлении или при удалении имени.
Консистенция как-то непонятно. Гугл говорит, что можно первести как последовательность

2017-01-02 20:18 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Манипуляция объектами приходящие в параметры может вызывать нежелательные побочные эффекты в вызывающей функции.
Не согласовано, надо `приходящими` и выделить запятыми тогда причастный оборот - `объектами, приходящими в параметры, может`

2017-01-02 21:46 UTC, leonidlebedev commented on README.md
> +    > Почему? Самовызывающееся функциональное выражение представляет собой единый блок, чтобы четко показать это, оберните вызывающие скобки в скобки. Обратите внимание, что в мире с модулями, вам бо
> Ещё меня терзают сомнения по поводу Самовызывающееся. Кажется, в литературе я встречала термин "немедленно вызываемые"

Дай ссылку на такую литературу.

2017-01-02 21:56 UTC, leonidlebedev commented
> Ещё меня терзают сомнения по поводу Самовызывающееся. Кажется, в литературе я встречала термин "немедленно вызываемые"

Дай ссылку на такую литературу.

2017-01-03 10:43 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Самовызывающееся функциональное выражение представляет собой единый блок, чтобы четко показать это, оберните вызывающие скобки в скобки. Обратите внимание, что в мире с модулями, вам бо
Ух, ну ты спросил, я уже не вспомню. Гугл знает и то, и то

2017-01-05 13:59 UTC, VictoriaMaksimova approved these changes

2017-01-05 19:20 UTC, merged