#8. Стрелочные функции
leonidlebedev/javascript-airbnb pull request #13
Opened 2017-01-02 13:20 UTC by leonidlebedev

2017-01-02 20:22 UTC, VictoriaMaksimova requested changes

2017-01-02 20:22 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Таким образом создаётся функция, которая выполняется в контексте `this`, которая обычно мы хотим, а также это более короткий синтаксис.
`в контексте `this`, который мы обычно хотим`

2017-01-02 20:22 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Синтаксический сахар. Это читается лучше, когда несколько функций соединены вместе.
Лучше поменять местами `Когда несколько функций соединены вместе, это читается лучше`

2017-01-02 20:22 UTC, VictoriaMaksimova commented on README.md
> +  - [8.4](#arrows--one-arg-parens) Если ваша функция принимает один аргумент и не использует фигурные скобки, то опустите круглые скобки. В противном случае, всегда оборачивайте аргументы скобками. e
оборачивайте аргументы _круглыми_ скобками?

2017-01-02 20:22 UTC, VictoriaMaksimova commented on README.md
> +  - [8.5](#arrows--confusing) Избегайте запутанной стрелочной функции (`=>`) с операторами сравнения (`<=`, `>=`). eslint: [`no-confusing-arrow`](http://eslint.org/docs/rules/no-confusing-arrow)
`Избегайте _схожести_ стрелочной функции`

2017-01-02 22:04 UTC, leonidlebedev commented
Надо переводить [это](https://github.com/leonidlebedev/javascript-airbnb/pull/13/files#diff-04c6e90faac2675aa89e2176d2eec7d8R928)?

2017-01-03 10:44 UTC, VictoriaMaksimova approved these changes

2017-01-04 18:22 UTC, merged