#9. Классы и конструкторы
leonidlebedev/javascript-airbnb pull request #14
Opened 2017-01-02 13:47 UTC by leonidlebedev

2017-01-02 20:31 UTC, VictoriaMaksimova requested changes

2017-01-02 20:31 UTC, VictoriaMaksimova commented on README.md
> +  - [9.3](#constructors--chaining) Методы могут возвращать `this`, чтобы помочь делать цепочки вызовов.
`помочь` можно убрать

2017-01-02 20:31 UTC, VictoriaMaksimova commented on README.md
> +  - [9.4](#constructors--tostring) Это нормально, написать свой собственный метод `toString()`, просто убедитесь, что она успешно работает и не вызывает никаких побочных эффектов.
что _он_ успешно работает и не _создает_ никаких

2017-01-02 20:31 UTC, VictoriaMaksimova commented on README.md
> +  - [9.5](#constructors--no-useless) У классов есть конструктор по умолчанию, если не указан другой конструктор. Не надо пустому конструктору или другому делегировать родительскому классу. eslint: [`
У классов есть конструктор по умолчанию _если он не задан явно. Пустой конструктор или конструктор, который только делегирует выполнение родительскому классу, можно опустить._

2017-01-02 20:31 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Повторяющиеся объявления членов класса отдают предпочтения последним. Дубликаты почти всегда вызывают ошибки.
_Из повторяющихся объявлений членов класса без предупрежения об ошибке будут использованы последние_

2017-01-02 22:07 UTC, leonidlebedev commented on README.md
> +  - [9.5](#constructors--no-useless) У классов есть конструктор по умолчанию, если не указан другой конструктор. Не надо пустому конструктору или другому делегировать родительскому классу. eslint: [`
Да, что-то я тут явно накосячил 😊

2017-01-02 22:09 UTC, leonidlebedev commented on README.md
> +    > Почему? Повторяющиеся объявления членов класса отдают предпочтения последним. Дубликаты почти всегда вызывают ошибки.
Как-то всё равно сложно.

2017-01-03 10:52 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Повторяющиеся объявления членов класса отдают предпочтения последним. Дубликаты почти всегда вызывают ошибки.
может как-то так
_Если объявление члена класса повторяется, без предупреждения будет использовано последнее - наличие дубликатов скорее всего означает ошибку._

2017-01-05 13:59 UTC, VictoriaMaksimova approved these changes

2017-01-05 19:20 UTC, merged