#19. Запятые
leonidlebedev/javascript-airbnb pull request #15
Opened 2017-01-02 21:16 UTC by VictoriaMaksimova

2017-01-02 22:19 UTC, leonidlebedev requested changes

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +  - [19.1](#commas--leading-trailing) Начинать строку с запятой: **Нет.** eslint: [`comma-style`](http://eslint.org/docs/rules/comma-style.html) jscs: [`requireCommaBeforeLineBreak`](http://jscs.info
Может тут отказаться от такого перевода, потому что я не сразу понял, пока не залез в пример.

`Не начинайте строку с запятой. eslint: `

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +  - [19.2](#commas--dangling) Висячие запятые: **Да.** eslint: [`comma-dangle`](http://eslint.org/docs/rules/comma-dangle.html) jscs: [`requireTrailingComma`](http://jscs.info/rule/requireTrailingCom
Тогда тут тоже надо будет изменить.

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +    > Почему? Такой подход даёт более понятную разницу при просмотре изменений. Кроме того, транспиляторы типа Babel удалят висячие запятые из собранного кода, поэтому вы можете не беспокоиться о [ п
Я предлагаю всё делать без `ё`. Так я переводил все пункты до этого.

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +    > Почему? Такой подход даёт более понятную разницу при просмотре изменений. Кроме того, транспиляторы типа Babel удалят висячие запятые из собранного кода, поэтому вы можете не беспокоиться о [ п
`более` можно опустить.

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +    > Почему? Такой подход даёт более понятную разницу при просмотре изменений. Кроме того, транспиляторы типа Babel удалят висячие запятые из собранного кода, поэтому вы можете не беспокоиться о [ п
`типа Babel` не надо в запятые?

2017-01-02 22:19 UTC, leonidlebedev commented on README.md
> +    > Почему? Такой подход даёт более понятную разницу при просмотре изменений. Кроме того, транспиляторы типа Babel удалят висячие запятые из собранного кода, поэтому вы можете не беспокоиться о [ п
`[ проблемах]` пробел лишний

2017-01-04 12:03 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Такой подход даёт более понятную разницу при просмотре изменений. Кроме того, транспиляторы типа Babel удалят висячие запятые из собранного кода, поэтому вы можете не беспокоиться о [ п
`типа Babel` кажется не надо, остальное ++

2017-01-04 18:14 UTC, leonidlebedev approved these changes

2017-01-04 18:24 UTC, merged