#20. Точка с запятой
leonidlebedev/javascript-airbnb pull request #16
Opened 2017-01-02 21:37 UTC by VictoriaMaksimova

2017-01-02 22:20 UTC, leonidlebedev requested changes

2017-01-02 22:20 UTC, leonidlebedev commented on README.md
> +    // хорошо, но уже устарело (такая защита функций нужна когда конкатернируются два файла, содержащие немедленно вызываемые функции)
Надо договориться об определении ** IIFE**

2017-01-02 22:21 UTC, leonidlebedev commented on README.md
> +    // хорошо, но уже устарело (такая защита функций нужна когда конкатернируются два файла, содержащие немедленно вызываемые функции)
Связано с PR #12

2017-01-04 12:24 UTC, VictoriaMaksimova commented on README.md
> +    // хорошо, но уже устарело (такая защита функций нужна когда конкатернируются два файла, содержащие немедленно вызываемые функции)
мне как-то больше нравится немедленно вызываемые. В самовызывающихся мне не нравится вот это "само", функция ж сама ничего не делает, её же программист вызывает в любом случае)

2017-01-04 18:38 UTC, leonidlebedev commented on README.md
> +    // хорошо, но уже устарело (такая защита функций нужна когда конкатернируются два файла, содержащие немедленно вызываемые функции)
Окей, так и сделал в PR #12

2017-01-04 18:41 UTC, leonidlebedev approved these changes

2017-01-05 13:50 UTC, merged