#27. ES6+
leonidlebedev/javascript-airbnb pull request #25
Opened 2017-01-07 18:57 UTC by VictoriaMaksimova

2017-01-07 19:22 UTC, leonidlebedev requested changes

2017-01-07 19:22 UTC, leonidlebedev commented on README.md
> +## <a name="ecmascript-6-es-2015-styles">ECMAScript 6+ (ES 2015+) Styles</a>
Здесь тоже надо перевести.

2017-01-07 19:22 UTC, leonidlebedev commented on README.md
> +1. [Оператор расширения](#es6-rest)
Хм, spread — оператор расширения, а rest немного другой.

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Operators/Spread_operator

2017-01-07 19:22 UTC, leonidlebedev commented on README.md
> +1. [Оператор расширения](#es6-rest)
Возможно стоит тогда поменять перевод в той части.

2017-01-07 19:22 UTC, leonidlebedev commented on README.md
> +  - [27.2](#tc39-proposals) Не используйте [предложения TC39](https://github.com/tc39/proposals) которые не перешли на 3 стадию.
Запятая в конце `]`?

2017-01-07 19:22 UTC, leonidlebedev commented on README.md
> +    > Почему? [Они ещё не закончены](https://tc39.github.io/process-document/), и они могут быть изменены или полностью изъяты. Мы хотим использовать JavaScript, а предложения это еще не JavaScript.
во втором случае можно убрать _они_

2017-01-07 20:29 UTC, leonidlebedev commented on README.md
> +
Появилась новая строка

2017-01-08 11:19 UTC, leonidlebedev requested changes

2017-01-08 11:19 UTC, leonidlebedev commented on README.md
> +    > Почему? `...` явно говорит о том, какие именно аргументы вы хотите извлечь. Кроме того, оператор оставшихся параметров создает настоящий массив, а не массиво-подобный объект как `arguments`.
_Кроме того, такой синтаксис создает ..._

2017-01-08 11:19 UTC, leonidlebedev commented on README.md
> +
Можно удалить строку

2017-01-08 11:19 UTC, leonidlebedev commented on README.md
> +    > Почему? [Они ещё не закончены](https://tc39.github.io/process-document/) и  могут быть изменены или полностью изъяты. Мы хотим использовать JavaScript, а предложения это еще не JavaScript.
Я бы перевел так:

Мы хотим использовать стабильные возможности `Javascript`, а не нестандартизированные предложения.

2017-01-08 13:12 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? [Они ещё не закончены](https://tc39.github.io/process-document/) и  могут быть изменены или полностью изъяты. Мы хотим использовать JavaScript, а предложения это еще не JavaScript.
Мне кажется нормально оставить так. Можно 
_Мы хотим использовать JavaScript, а предложения еще не стали частью JavaScript_

2017-01-08 19:22 UTC, leonidlebedev commented on README.md
> +    > Почему? [Они ещё не закончены](https://tc39.github.io/process-document/) и  могут быть изменены или полностью изъяты. Мы хотим использовать JavaScript, а предложения это еще не JavaScript.
Можно и так.

2017-01-10 21:44 UTC, leonidlebedev approved these changes

2017-01-11 23:00 UTC, merged