Изменения по итогам всего документа
leonidlebedev/javascript-airbnb pull request #30
Opened 2017-01-10 23:49 UTC by leonidlebedev

2017-01-11 23:05 UTC, VictoriaMaksimova requested changes

2017-01-11 23:05 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Это гарантирует, что вы не сможете переопределить значения, которые могут привести к ошибкам и к трудночитаемому коду.
Раньше было лучше, теперь получается что значения могут привести. А смысл, что переопределения могут привести

2017-01-14 11:29 UTC, leonidlebedev commented
@VictoriaMaksimova, исправил твои замечания.

2017-01-14 11:53 UTC, VictoriaMaksimova approved these changes

2017-01-14 14:06 UTC, merged