Перечитаны первые 10 пунктов, немного поправлены
leonidlebedev/javascript-airbnb pull request #31
Opened 2017-01-14 21:43 UTC by VictoriaMaksimova

2017-01-14 22:46 UTC, leonidlebedev requested changes

2017-01-14 22:46 UTC, leonidlebedev commented on README.md
> +  > Почему? В общем мы считаем, что это субъективно легче читать. Это улучшает подсветку синтаксиса, а также облегчает оптимизацию для многих JS движков.
Здесь же вводное слово, поэтому запятая нужна. 

http://new.gramota.ru/spravka/punctum?layout=item&id=58_291

2017-01-14 22:46 UTC, leonidlebedev commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле, а это вредит читабельности и поддержке. Если вы обнаружите, что опред
А что тут поменялось?

2017-01-15 22:58 UTC, VictoriaMaksimova commented on README.md
> +  > Почему? В общем мы считаем, что это субъективно легче читать. Это улучшает подсветку синтаксиса, а также облегчает оптимизацию для многих JS движков.
Мне кажется, здесь оно не вводное. Посмотри там у правила вторую часть
! Не смешивать с употреблением в роли члена предложения (в знач. «в общих чертах, в целом, не вдаваясь в детали»).

2017-01-15 22:59 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле, а это вредит читабельности и поддержке. Если вы обнаружите, что опред
Вообще тут я дефис заменила на тире, странно, что не подсвечивается

2017-01-16 07:33 UTC, leonidlebedev approved these changes

2017-01-16 07:54 UTC, merged