Перечитала пункты с 11 и до конца, немного поправила
leonidlebedev/javascript-airbnb pull request #32
Opened 2017-01-16 21:47 UTC by VictoriaMaksimova

2017-01-16 21:55 UTC, leonidlebedev requested changes

2017-01-16 21:55 UTC, leonidlebedev commented on README.md
> +  - [14.4](#hoisting--declarations) Для объявлений функций наверх области видимости поднимаются имя и тело функций.
Раза с третьего только понял о чём речь.

2017-01-16 21:55 UTC, leonidlebedev commented on README.md
> +  - [15.5](#comparison--switch-blocks) Используйте фигурные скобки для `case` и `default`, если они содержат лексические декларации (например, `let`, `const`, `function`, и `class`). eslint: [`no-cas
Вот за это лайк! Тоже хотел исправить) 👍

2017-01-16 21:55 UTC, leonidlebedev commented on README.md
> +  - [21.4](#coercion--comment-deviations) Если по какой-то причине вы делаете что-то безумное, для чего `parseInt` является слабым местом и вам нужно использовать побитовый сдвиг из-за [вопросов прои
Звучит странно. Раньше нормально было.

2017-01-16 21:58 UTC, VictoriaMaksimova commented on README.md
> +  - [14.4](#hoisting--declarations) Для объявлений функций наверх области видимости поднимаются имя и тело функций.
Ага, зубодробительно. В едином стиле с предыдущими пунктами про подъем

2017-01-16 21:59 UTC, VictoriaMaksimova commented on README.md
> +  - [21.4](#coercion--comment-deviations) Если по какой-то причине вы делаете что-то безумное, для чего `parseInt` является слабым местом и вам нужно использовать побитовый сдвиг из-за [вопросов прои
Раньше смысл был немного не тот, как в оригинале

2017-01-17 07:52 UTC, leonidlebedev commented on README.md
> +  - [14.4](#hoisting--declarations) Для объявлений функций наверх области видимости поднимаются имя и тело функций.
Как тебе такие варианты?
> При объявлении функции его имя и тело поднимаются наверх области видимости.

> Для объявлений функций свойственно поднимать наверх области видимости имя и тело функций.

2017-01-17 07:53 UTC, leonidlebedev commented on README.md
> +  - [21.4](#coercion--comment-deviations) Если по какой-то причине вы делаете что-то безумное, для чего `parseInt` является слабым местом и вам нужно использовать побитовый сдвиг из-за [вопросов прои
> Для чего `parseInt` является слабым местом
Вот это странно

2017-01-17 08:15 UTC, VictoriaMaksimova commented on README.md
> +  - [14.4](#hoisting--declarations) Для объявлений функций наверх области видимости поднимаются имя и тело функций.
Вот этот хорош, только `ее` наверно, не `его`
`При объявлении функции его имя и тело поднимаются наверх области видимости`

2017-01-17 08:17 UTC, VictoriaMaksimova commented on README.md
> +  - [21.4](#coercion--comment-deviations) Если по какой-то причине вы делаете что-то безумное, для чего `parseInt` является слабым местом и вам нужно использовать побитовый сдвиг из-за [вопросов прои
Может так
Если по какой-то причине вы делаете что-то настолько безумное, что `parseInt` является слабым местом и вам нужно использовать побитовый сдвиг из-за

2017-01-17 19:26 UTC, nialvi commented on README.md
> +  - [21.5](#coercion--bitwise) **Примечание:** Будьте осторожны с побитовыми операциями.Числа в JavaScript являются [64-битными значениями](https://es5.github.io/#x4.3.19), но побитовые операции всег
блин, мне даже стыдно про это писать, но типографика все же.
после точки пробел
"Будьте осторожны с побитовыми операциями.Числа"

2017-01-17 20:15 UTC, leonidlebedev approved these changes

2017-01-17 21:22 UTC, merged