Перевод заголовка и описания
leonidlebedev/javascript-airbnb pull request #38
Opened 2017-02-05 13:19 UTC by leonidlebedev

2017-02-06 20:21 UTC, VictoriaMaksimova requested changes

2017-02-06 20:21 UTC, VictoriaMaksimova commented on react/README.md
> +*В основном разумный подход к написанию React и JSX*
ДУмаю тут имеется в виду `наиболее разумный`

2017-02-07 20:32 UTC, leonidlebedev commented on react/README.md
> +*В основном разумный подход к написанию React и JSX*
Холиварно, оставим для единообразия

2017-02-07 20:37 UTC, VictoriaMaksimova approved these changes

2017-02-08 07:00 UTC, merged