Перевод основных правил
leonidlebedev/javascript-airbnb pull request #39
Opened 2017-02-05 15:30 UTC by leonidlebedev

2017-02-06 20:20 UTC, VictoriaMaksimova requested changes

2017-02-06 20:20 UTC, VictoriaMaksimova commented on react/README.md
> +## Class против `React.createClass` против компонента без состояний (stateless)
Я бы использовала `или`
Class или `React.createClass` или stateless

2017-02-06 20:20 UTC, VictoriaMaksimova commented on react/README.md
> +  - Если у вас есть внутреннее состояние (`state`) и/или ссылки (`refs`), отдавайте предпочтение `class extends React.Component` вместо `React.createClass`, если у вас нет резких причин использовать
лучше - `веских причин`

2017-02-12 20:47 UTC, leonidlebedev commented on react/README.md
> +## Class против `React.createClass` против компонента без состояний (stateless)
Я бы так оставил. Здесь же смысл противопоставления.

2017-02-12 20:52 UTC, VictoriaMaksimova commented on react/README.md
> +## Class против `React.createClass` против компонента без состояний (stateless)
Ok

2017-02-12 20:52 UTC, VictoriaMaksimova approved these changes

2017-02-12 21:18 UTC, merged