React #3 Naming translation
leonidlebedev/javascript-airbnb pull request #40
Opened 2017-02-12 20:43 UTC by VictoriaMaksimova

2017-02-12 21:18 UTC, leonidlebedev requested changes

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Названия компонентов высшего порядка**: Составляйте имя из названия компонента высшего порядка и названия переданного компонента, сохраняя его в свойстве `displayName` сгенерированного компонен
Сложно как-то вышло. Может такой вариант?
`Используйте сочетание имени компонента высшего порядка и имени переданного в него компонента, как свойство displayName сгенерированного компонента.`

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  > Почему? Свойство `displayName` может быть использовано в инструментах разработчика или сообщениях об ошибках, и если оно ясно выражает отношения между компонетами, это помогает людям понять, что
`связь между компонеНтами`

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Названия файлов**: Используйте `PascalCase` для названий файлов, например, `ReservationCard.jsx`.
`Имя файла`

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Названия переменных**: Используйте `PascalCase` для компонентов React и `camelCase` для их экземпляров. eslint: [`react/jsx-pascal-case`](https://github.com/yannickcr/eslint-plugin-react/blob/m
Тут же не только про переменные.
И почему везде `Название`, хотя должно быть `Именование`
`Именование ссылок`

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Названия компонентов**: Называйте файлы также как и компоненты. Например, `ReservationCard.jsx` должен содержать внутри компонент `ReservationCard`. Однако корневые компоненты в директории долж
`Именование компонента`
Одного компонента

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Названия компонентов высшего порядка**: Составляйте имя из названия компонента высшего порядка и названия переданного компонента, сохраняя его в свойстве `displayName` сгенерированного компонен
Тоже самое про `Именование` и единственное число.

2017-02-12 21:18 UTC, leonidlebedev commented on react/README.md
> +  - **Расширения**: Используйте расширение `.jsx` для компонентов React.
Почему наоборот вышло? Логично же `React компонентов`

2017-02-18 11:49 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Названия переменных**: Используйте `PascalCase` для компонентов React и `camelCase` для их экземпляров. eslint: [`react/jsx-pascal-case`](https://github.com/yannickcr/eslint-plugin-react/blob/m
Именование ок
Про `ссылок` не согласна, нет у нас такого понятия. Похожий спор у нас был и когда переводили основной стайл гайд, сравни п2 у нас и в оргинале
https://github.com/leonidlebedev/javascript-airbnb#references
https://github.com/airbnb/javascript/#references

2017-02-18 11:59 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Расширения**: Используйте расширение `.jsx` для компонентов React.
Не вижу разницы

2017-02-18 12:02 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Названия файлов**: Используйте `PascalCase` для названий файлов, например, `ReservationCard.jsx`.
++

2017-02-18 12:02 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Названия компонентов**: Называйте файлы также как и компоненты. Например, `ReservationCard.jsx` должен содержать внутри компонент `ReservationCard`. Однако корневые компоненты в директории долж
++

2017-02-18 12:02 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Названия компонентов высшего порядка**: Составляйте имя из названия компонента высшего порядка и названия переданного компонента, сохраняя его в свойстве `displayName` сгенерированного компонен
Да, так лучше

2017-02-18 12:03 UTC, VictoriaMaksimova commented on react/README.md
> +  - **Названия компонентов высшего порядка**: Составляйте имя из названия компонента высшего порядка и названия переданного компонента, сохраняя его в свойстве `displayName` сгенерированного компонен
++

2017-02-18 12:03 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Свойство `displayName` может быть использовано в инструментах разработчика или сообщениях об ошибках, и если оно ясно выражает отношения между компонетами, это помогает людям понять, что
++

2017-02-18 13:49 UTC, leonidlebedev approved these changes

2017-02-18 19:36 UTC, merged