React #4 Declaration
leonidlebedev/javascript-airbnb pull request #41
Opened 2017-02-12 20:52 UTC by VictoriaMaksimova

2017-02-12 21:21 UTC, leonidlebedev requested changes

2017-02-12 21:21 UTC, leonidlebedev commented on react/README.md
> +  - Не используйте свойство `displayName` для названий компонентов. Вместо этого задавайте имя классу компонента.
`для именования`?

2017-02-12 21:21 UTC, leonidlebedev commented on react/README.md
> +  - Не используйте свойство `displayName` для названий компонентов. Вместо этого задавайте имя классу компонента.
`именуйте компонент по ссылке`?

2017-02-18 13:50 UTC, leonidlebedev commented
@VictoriaMaksimova, необходимо пофиксить конфликты.

2017-02-18 19:38 UTC, VictoriaMaksimova commented on react/README.md
> +  - Не используйте свойство `displayName` для названий компонентов. Вместо этого задавайте имя классу компонента.
Именования ок
Про `by reference` долго думала, не знаю. Тут опять же нет у нас эквивалентного понятия, кажется, в данном случае ближе всего по смылу `класс`

2017-02-19 00:17 UTC, nialvi approved these changes

2017-02-20 07:47 UTC, leonidlebedev approved these changes

2017-02-20 12:25 UTC, merged