Перевод Примеси
leonidlebedev/javascript-airbnb pull request #45
Opened 2017-02-24 08:15 UTC by leonidlebedev

2017-02-24 18:52 UTC, nialvi approved these changes

2017-03-01 20:03 UTC, VictoriaMaksimova requested changes

2017-03-01 20:03 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Примечи вносят неявные зависимости, становятся причиной конфликтов имен и быстрого роста сложностей. Большинство случаев, для которых используется примеси, могут выполняться более эффекти
`ПримеСи вносят`

2017-03-01 20:03 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Примечи вносят неявные зависимости, становятся причиной конфликтов имен и быстрого роста сложностей. Большинство случаев, для которых используется примеси, могут выполняться более эффекти
`используЮтся примеси`

2017-03-01 20:03 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Примечи вносят неявные зависимости, становятся причиной конфликтов имен и быстрого роста сложностей. Большинство случаев, для которых используется примеси, могут выполняться более эффекти
Смущает формулировка `Большинство случаев ... могут выполняться`. Случаи не могут выполняться.
Кажется лучше так
`Для большинства случаев, в которых используются примеси, можно более эффективно применить компоненты, компоненты высшего порядка или полезные модули.`

2017-03-01 20:03 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Примечи вносят неявные зависимости, становятся причиной конфликтов имен и быстрого роста сложностей. Большинство случаев, для которых используется примеси, могут выполняться более эффекти
`Полезные модули` это употребляемый термин? Уточняю, я просто не в курсе

2017-03-01 22:06 UTC, leonidlebedev commented on react/README.md
> +  > Почему? Примечи вносят неявные зависимости, становятся причиной конфликтов имен и быстрого роста сложностей. Большинство случаев, для которых используется примеси, могут выполняться более эффекти
@VictoriaMaksimova, utility modules в оригинале

2017-03-03 07:46 UTC, VictoriaMaksimova approved these changes

2017-03-03 22:38 UTC, merged