Перевод props
leonidlebedev/javascript-airbnb pull request #47
Opened 2017-02-24 08:53 UTC by leonidlebedev

2017-02-24 19:16 UTC, nialvi approved these changes

2017-03-01 20:10 UTC, VictoriaMaksimova requested changes

2017-03-01 20:10 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Несоответствия между сочетанием комбинаций клавиш и командами с клавиатуры, затрудняют доступ для людей, которые пользуются экранными считывателями и клавиатурами.
Не нужны запятая `с клавиатуры, затрудняют`

2017-03-01 20:10 UTC, VictoriaMaksimova commented on react/README.md
> +  - Избегайте использовать индексы элементов массива в качестве свойства `key`, и отдавайте предпочтение уникальному ID. ([почему?](https://medium.com/@robinpokorny/index-as-a-key-is-an-anti-pattern-
Не нужна запятая `, и отдавайте`

2017-03-01 20:10 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? `propTypes` является способом документации, а также предоставление `defaultProps` позволяет читателю вашего кода не иметь множество неясностей. Кроме того, это может означать, что ваш код
`а также` лучше убрать или заменить на `и`

2017-03-01 22:10 UTC, leonidlebedev commented on react/README.md
> +  > Почему? `propTypes` является способом документации, а также предоставление `defaultProps` позволяет читателю вашего кода не иметь множество неясностей. Кроме того, это может означать, что ваш код
Лучше просто на `a`

2017-03-05 11:04 UTC, VictoriaMaksimova approved these changes

2017-03-05 11:18 UTC, merged