Перевод parentheses
leonidlebedev/javascript-airbnb pull request #49
Opened 2017-02-24 12:10 UTC by leonidlebedev

2017-02-24 19:22 UTC, nialvi approved these changes

2017-03-01 20:12 UTC, VictoriaMaksimova requested changes

2017-03-01 20:12 UTC, VictoriaMaksimova commented on react/README.md
> +  1. [Скобки](#parentheses)
Круглые скобки

2017-03-01 20:13 UTC, VictoriaMaksimova requested changes

2017-03-01 20:13 UTC, VictoriaMaksimova commented on react/README.md
> +  - Оборачивайте в скобки JSX теги, когда они занимают больше одной строки. eslint: [`react/jsx-wrap-multilines`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/jsx-wrap-mult
Вообще в заголовке можно оставить без "Круглые", но тут точно стоит добавить

2017-03-05 11:04 UTC, VictoriaMaksimova approved these changes

2017-03-05 11:18 UTC, merged