#18. Пробелы
leonidlebedev/javascript-airbnb pull request #5
Opened 2017-01-01 22:26 UTC by VictoriaMaksimova

2017-01-01 23:12 UTC, leonidlebedev requested changes

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +## Пробелы
Здесь также надо сделать ссылкой.

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.1](#whitespace--spaces) Используйте мягкие отступы шириной в 2 пробела. eslint: [`indent`](http://eslint.org/docs/rules/indent.html) jscs: [`validateIndentation`](http://jscs.info/rule/valida
`soft tabs` — мягкая табуляция.

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.2](#whitespace--before-blocks) Оставляйте 1 пробел перед открывающей фигурной скобкой у блока. eslint: [`space-before-blocks`](http://eslint.org/docs/rules/space-before-blocks.html) jscs: [`r
Ставьте 1 пробел

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.3](#whitespace--around-keywords) Оставляйте 1 пробел перед открывающей круглой скобкой в операторах управления (`if`, `while` и т.п.). Не оставляйте пробелов между списком аргументов и назван
Тоже c `Place`

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.2](#whitespace--before-blocks) Оставляйте 1 пробел перед открывающей фигурной скобкой у блока. eslint: [`space-before-blocks`](http://eslint.org/docs/rules/space-before-blocks.html) jscs: [`r
Устанавливайте 1 пробел

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.3](#whitespace--around-keywords) Оставляйте 1 пробел перед открывающей круглой скобкой в операторах управления (`if`, `while` и т.п.). Не оставляйте пробелов между списком аргументов и назван
в объявлениЯх

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.6](#whitespace--chains) Используйте переносы строк и отступы, когда вызываете больше 2 методов по цепочке. Ставьте точку в начале строки перед такими методами, чтобы дать понять, что это не н
Мой вариант:
`Используйте переносы строк и отступы, когда делаете длинные цепочки методов (больше 2-х методов)`

Для себя я усвоил, что `statement` переводится как `инструкция`.

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +  - [18.7](#whitespace--after-blocks) Оставляйте пустую строку между блоком кода и следующим выражением. jscs: [`requirePaddingNewLinesAfterBlocks`](http://jscs.info/rule/requirePaddingNewLinesAfterB
Также инструкция.

2017-01-01 23:12 UTC, leonidlebedev commented on README.md
> +    > Почему? Это обеспечивает удобство чтения и поддержки кода.
обеспечивает что? поддержку кода

2017-01-02 13:32 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Это обеспечивает удобство чтения и поддержки кода.
Не, тут не так. Удобство чего? чтения и поддержки

2017-01-02 13:59 UTC, leonidlebedev commented on README.md
> +  - [18.12](#whitespace--max-len) Старайтесь не допускать, чтобы строки были длиннее 100 символов (включая пробелы). Замечание: согласно [above](#strings--line-length), длинные строки с текстом освоб
Окей, надо ещё перевести `[above]`

2017-01-02 21:12 UTC, leonidlebedev approved these changes

2017-01-02 21:18 UTC, merged