Перевод tags
leonidlebedev/javascript-airbnb pull request #50
Opened 2017-02-24 12:16 UTC by leonidlebedev

2017-02-24 19:31 UTC, nialvi approved these changes

2017-03-01 20:17 UTC, VictoriaMaksimova requested changes

2017-03-01 20:17 UTC, VictoriaMaksimova commented on react/README.md
> +  - Всегда самозакрывайте теги, которые не имеют потомков. eslint: [`react/self-closing-comp`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/self-closing-comp.md)
Самозакрывайте?) И тут не про потомков. Лучше перефразировать как-то так
`Всегда используйте самозакрывающиеся теги, если у элемента нет дочерних`.

2017-03-05 11:04 UTC, VictoriaMaksimova approved these changes

2017-03-05 11:17 UTC, merged