Перевод methods
leonidlebedev/javascript-airbnb pull request #51
Opened 2017-02-24 12:38 UTC by leonidlebedev

2017-02-24 19:39 UTC, nialvi approved these changes

2017-03-01 20:22 UTC, VictoriaMaksimova requested changes

2017-03-01 20:22 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Префиксы подчеркивания иногда используются в других языках, как соглашение о приватности. Но, в отличие от этих языков, в Javascript нет нативной поддержки приватности, все публично. Неза
`и любЫе свойствА (с подчеркиванием или без) `

2017-03-01 20:22 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Префиксы подчеркивания иногда используются в других языках, как соглашение о приватности. Но, в отличие от этих языков, в Javascript нет нативной поддержки приватности, все публично. Неза
Не нужна запятая `языках, как соглашение`

2017-03-01 20:22 UTC, VictoriaMaksimova commented on react/README.md
> +  - Будьте уверенным, что вы возвращаете значение в методе `render`. eslint: [`react/require-render-return`](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/require-render-ret
Звучит странно, лучше переформулировать. И там множественное число
`Всегда возвращайте значение в методАХ`

2017-03-05 11:06 UTC, VictoriaMaksimova requested changes

2017-03-05 11:06 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? Префиксы подчеркивания иногда используются в других языках как соглашение о приватности. Но, в отличие от этих языков, в Javascript нет нативной поддержки приватности, все публично. Незав
`должны рассматриваться как публичныЕ`

2017-03-05 11:21 UTC, VictoriaMaksimova approved these changes

2017-03-05 11:21 UTC, merged