Перевод isMounted
leonidlebedev/javascript-airbnb pull request #53
Opened 2017-02-24 12:50 UTC by leonidlebedev

2017-02-24 19:43 UTC, nialvi approved these changes

2017-03-01 20:24 UTC, VictoriaMaksimova requested changes

2017-03-01 20:24 UTC, VictoriaMaksimova commented on react/README.md
> +  > Почему? [`isMounted` — это антипаттерн][anti-pattern], который недоступен при использовании ES6 классов и, который планируют официально признать устаревшим.
Тут после `isMounted` длинное тире?
Не нужна зпт  `классов и, который`

2017-03-01 22:18 UTC, leonidlebedev commented on react/README.md
> +  > Почему? [`isMounted` — это антипаттерн][anti-pattern], который недоступен при использовании ES6 классов и, который планируют официально признать устаревшим.
Да, там длинное тире.

2017-03-05 11:06 UTC, VictoriaMaksimova approved these changes

2017-03-05 11:16 UTC, merged