Обновил руководство
leonidlebedev/javascript-airbnb pull request #58
Opened 2017-10-01 07:18 UTC by agladky

- Добавил пункт про использование babel
- Изменил пункт 4.4 про преобразование объекта в массив
- Добавил пункт 4.5 про применение отображений на массив
- Добавил пункт 12.3 про оператор возведения в степень `**`
- Добавил секцию про «Стандартную библиотеку»
- Обновил список «В реальной жизни»
- Добавил ссылку на украинскую локализацию
- Добавил секцию «Поправки»

2017-10-01 13:46 UTC, leonidlebedev commented
@agladky, Спасибо большое за PR!

2017-10-01 14:27 UTC, leonidlebedev requested changes

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +  - [4.5](#arrays--mapping) Используйте [Array.from](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from) вместо оператора расширения `...` для применения отображ
> для применения отображения на элементы

А что значит эта фраза?

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +Мы рекомендуем вам сделать форк этого руководства и изменить его под стиль вашей команды. Ниже вы можете перечислить свои изменения в руководстве. Это позволяет периодически обновлять его, не сталкив
- `изменить его` правила
- Это позволит вам обновлять его время от времени, не сталкиваясь с конфликтами слияний.

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +    > Почему? Глобальная функция `isNaN` приводит не-числа к числам, возвращая true для всего что приводится к NaN.
`не-числа` здесь дефис не нужен (тоже самое ниже).
**true** и **NaN** можно взять в ``, чтоб легче читалось (опционально).

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +**[⬆ back to top](#table-of-contents)**
`**[⬆ к оглавлению](#Оглавление)**`

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +  [Стандартная библиотека](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects)
Можно дать ссылку на русскую доку 
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +  - [4.5](#arrays--mapping) Используйте [Array.from](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from) вместо оператора расширения `...` для применения отображ
Можно дать русскую ссылку
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +  - [4.4](#arrays--from) Для преобразования массиво-подобного объекта в массив используйте оператор расширения `...` вместо [Array.from](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference
Если не сложно, то замени здесь тоже ссылку
https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array/from

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +> **Замечание**: этот гид подразумевает использование [Babel](https://babeljs.io) вместе с [babel-preset-airbnb](https://npmjs.com/babel-preset-airbnb) или аналогом. Он также подразумевает установлен
`Это руководство`
Соответственно, дальше надо поправить род.

2017-10-01 14:27 UTC, leonidlebedev commented on README.md
> +> **Замечание**: этот гид подразумевает использование [Babel](https://babeljs.io) вместе с [babel-preset-airbnb](https://npmjs.com/babel-preset-airbnb) или аналогом. Он также подразумевает установлен
Два раза `подразумевает`, можно заменить на `предполагает`

2017-10-01 17:01 UTC, agladky commented on README.md
> +  - [4.5](#arrays--mapping) Используйте [Array.from](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from) вместо оператора расширения `...` для применения отображ
В оригинале:
 > for mapping over iterables

Как еще можно mapping перевести? Я обычно перевожу «отображение»  или «маппинг».

2017-10-02 07:44 UTC, VictoriaMaksimova requested changes

2017-10-02 07:44 UTC, VictoriaMaksimova commented on README.md
> +  - [4.5](#arrays--mapping) Используйте [Array.from](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Array/from) вместо оператора расширения `...` для применения отображ
Кмк тут лучше использовать кальку -- "маппинг", так точно понятно
`для маппинга итерируемых объектов`

Лучше в настоящем времени: `это позволяет избежать` вместо `это позволит`

2017-10-02 07:44 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Глобальная функция `isNaN` приводит не-числа к числам, возвращая true для всего что приводится к NaN.
Перед `что приводится` запятая, ниже тоже

2017-10-02 12:03 UTC, VictoriaMaksimova approved these changes

2017-10-02 13:21 UTC, leonidlebedev approved these changes

2017-10-02 13:21 UTC, merged

2017-10-02 13:22 UTC, leonidlebedev commented
@agladky, спасибо! 💪