Обновление Функций
leonidlebedev/javascript-airbnb pull request #63
Opened 2017-10-24 11:14 UTC by leonidlebedev

https://github.com/airbnb/javascript/commit/3c6d40ccca6c436b7628c6fd3d2fe6a7eb9aae1a

2017-10-24 21:04 UTC, VictoriaMaksimova requested changes

2017-10-24 21:04 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле, но это вредит читабельности и поддержке. Если вы обнаружили, что опре
Я бы добавила прилагательное `Не забудьте явно назвать функционально выражение`

2017-10-24 21:04 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле, но это вредит читабельности и поддержке. Если вы обнаружили, что опре
А что вот тут имеется в виду, что-то я не догоняю о чём речь `что часто бывает в современных браузерах или при использовании компиляторов, таких как Babel`?

2017-10-24 21:04 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? У объявлений функций есть подъем. Это означает, что можно использовать функцию до того, как она определена в файле, но это вредит читабельности и поддержке. Если вы обнаружили, что опре
Надо добавить запятую `предположения, сделанные`
Хотя я бы последнюю фразу вообще поменяла `Это помогает точнее определять место ошибки по стеку вызовов.`

2017-10-27 10:52 UTC, leonidlebedev commented
> А что вот тут имеется в виду, что-то я не догоняю о чём речь `что часто бывает в современных браузерах или при использовании компиляторов, таких как Babel`?

https://github.com/airbnb/javascript/issues/794#issuecomment-285867184

2017-11-01 18:39 UTC, VictoriaMaksimova approved these changes

2017-11-02 06:06 UTC, merged