Перевод пояснения про точку с запятой
leonidlebedev/javascript-airbnb pull request #68
Opened 2018-01-05 22:20 UTC by leonidlebedev

2018-01-14 20:08 UTC, VictoriaMaksimova requested changes

2018-01-14 20:08 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Когда JavaScript встречает перенос строки без точки с запятой, он ипользует правило под названием [Автоматическая Вставка Точки с запятой (Automatic Semicolon Insertion)](https://tc39.g
Нужна запятая: `чтобы определить, стоит ли`

2018-01-14 20:08 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Когда JavaScript встречает перенос строки без точки с запятой, он ипользует правило под названием [Автоматическая Вставка Точки с запятой (Automatic Semicolon Insertion)](https://tc39.g
Не нужна запятая `как конец выражения и`

2018-01-14 20:08 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Когда JavaScript встречает перенос строки без точки с запятой, он ипользует правило под названием [Автоматическая Вставка Точки с запятой (Automatic Semicolon Insertion)](https://tc39.g
Я бы убрала "ваш" отсюда `истолкует ваш перенос строки`

2018-01-14 20:08 UTC, VictoriaMaksimova commented on README.md
> +    > Почему? Когда JavaScript встречает перенос строки без точки с запятой, он ипользует правило под названием [Автоматическая Вставка Точки с запятой (Automatic Semicolon Insertion)](https://tc39.g
Я бы перефразировала `помогут предотвратить вас от возникновение проблем` - `помогут вам предотвратить возникновение проблем`

2018-01-16 19:59 UTC, leonidlebedev commented
@VictoriaMaksimova, done

2018-01-16 20:26 UTC, VictoriaMaksimova approved these changes

2018-01-16 20:48 UTC, merged