Перевод пункта об именовании
leonidlebedev/javascript-airbnb pull request #71
Opened 2018-03-11 09:53 UTC by leonidlebedev

2018-03-21 13:12 UTC, VictoriaMaksimova requested changes

2018-03-21 13:12 UTC, VictoriaMaksimova commented on css-in-javascript/README.md
> +  - Используйте верблюжийРегистр для ключей объекта (т.е. "селекторы").
)) camelCase кажется вполне можно оставить

2018-03-21 13:12 UTC, VictoriaMaksimova commented on css-in-javascript/README.md
> +    > Почему? Мы получаем доступ к этим ключам, как свойства объекта `styles` в компоненте, поэтому удобнее использовать верблюжийРегистр.
`свойстваМ`

2018-03-21 13:12 UTC, VictoriaMaksimova commented on css-in-javascript/README.md
> +    > Почему? Подобно БЭМ, это солгашение дает понять, что стили предназначены для модификации элемента, которому предшествует символ подчеркивания. Подчеркивания не надо брать в кавычки, поэтому они
опечатка `солгашение`

2018-03-21 13:12 UTC, VictoriaMaksimova commented on css-in-javascript/README.md
> +    > Почему? Подобно модификаторам, сохранение солгасованности имен помогает обнаружить взаимосвязь этих стилей и стилями, которые переопределяют их в подходящих браузерах.
`этих стилей **со** стилями`

2018-03-21 13:12 UTC, VictoriaMaksimova commented on css-in-javascript/README.md
> +  - Используйте абстрактные имена (т.к. "small", "medium" и "large"), чтобы назвать контрольные точки медиа выражений.
`т.к.` это сокращение для "так как", а не "такие как", лучше написать полностью

2018-03-22 19:48 UTC, leonidlebedev commented
@VictoriaMaksimova, исправил

2018-03-26 11:45 UTC, VictoriaMaksimova approved these changes

2018-03-26 19:37 UTC, merged