#2. Ссылки
leonidlebedev/javascript-airbnb pull request #8
Opened 2017-01-02 10:50 UTC by leonidlebedev

2017-01-02 13:53 UTC, VictoriaMaksimova requested changes

2017-01-02 13:53 UTC, VictoriaMaksimova commented on README.md
> +  - [2.1](#references--prefer-const) Используйте `const` для всех ваших ссылок; избегайте `var`. eslint: [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), [`no-const-assign`](http://e
Тут мне кажется надо как-то по-другому сказать, не `ссылок`. Речь идёт видимо вообще про все переменные.

2017-01-02 13:56 UTC, VictoriaMaksimova commented on README.md
> +  - [2.1](#references--prefer-const) Используйте `const` для всех ваших ссылок; избегайте `var`. eslint: [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), [`no-const-assign`](http://e
Может быть `для объявления переменных`. Я бы таким и заголовок сделала

2017-01-02 14:03 UTC, leonidlebedev commented on README.md
> +  - [2.1](#references--prefer-const) Используйте `const` для всех ваших ссылок; избегайте `var`. eslint: [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), [`no-const-assign`](http://e
Угу, только есть специальный пункт про переменные. Вот здесь и возникает загвоздка 😊

2017-01-02 14:15 UTC, leonidlebedev commented on README.md
> +    // const и let существуют только в том блоке, в котором они определены
Нужна точка

2017-01-02 20:48 UTC, VictoriaMaksimova commented on README.md
> +  - [2.1](#references--prefer-const) Используйте `const` для всех ваших ссылок; избегайте `var`. eslint: [`prefer-const`](http://eslint.org/docs/rules/prefer-const.html), [`no-const-assign`](http://e
Может пусть там будут `переменные`, а тут `объявление переменных`

2017-01-04 11:58 UTC, VictoriaMaksimova approved these changes

2017-01-04 18:12 UTC, merged